from .keyboard_homework import register_keyboard_homework_handlers
from .homework import register_homework_handlers
from .update_homework import register_update_homework_handlers
from .homework_for_day import register_handlers_homework_for_day